#page title
page_title                                : Mind Connect                              # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Mind Connect                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The current coronavirus pandemic has resulted in social distancing measures that have separated us from our friends, family members and those who we turn to for emotional support. This has left many unaware of or unable to access timely support for our mental health.

enable_smart_app_banner                   : false                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                
your_link                                 :                     
your_city                                 :                              
email_address                             :
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : The Problem
    description                           : The pandemic has undeniably changed the fabric of our society, in ways we have yet to realise. Financial uncertainty, physical isolation from our social circle, worry for our loved ones and work-life frustrations are among those that plague us. Perhaps the most unsettling effect of the pandemic is one that poses a direct impact on our mental health.
    fontawesome_icon_name                 : magic
    
  - title                                 : Solution
    description                           : Connect, Match and Keep your mind healthy.
    fontawesome_icon_name                 : mobile

  - title                                 : Creation
    description                           : Everyone’s mental health is unique, why shouldn’t our support be? MindConnect is the smartest way to connect you to accredited, trained volunteers to provide emotional support and companionship using a matching-system and daily mood assessment tracking. Ultimately tackling the effects of loneliness and feelings of anxiety or depression.
    fontawesome_icon_name                 : play-circle

  - title                                 : Delivery
    description                           : Virtualization of mental health support using an app-based platform, allowing scalability of mental health support (IOS and Android) via the following features, separated into high level features and additional features.
    fontawesome_icon_name                 : sync

  - title                                 : One-to-one support
    description                           : A volunteer trained in wellbeing, with DBS certification, will be matched using AI volunteer-user matching system. According to research, therapists with modalities highly similar to their clients led to the most positive psychological outcomes (Winter, 1998).
    fontawesome_icon_name                 : adjust
  
  - title                                 : Mood tracker
    description                           : Feelings and mood can be logged day to day using interactive evidence based 12-item MDMQ Assessment Questionnaire. This is recorded to inform volunteers and users of progress to enable timely support and future research purposes. 
    fontawesome_icon_name                 : star

  - title                                 : Group support
    description                           : An ‘explore’ page for inspirational and educational material, regulated by volunteers; latest evidence based recommendations, general mental wellbeing advice/tips, lifestyle recommendations (books, exercise etc.) and blog posts.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : The Future of Mind Connect
    description                           : Long term effects of the pandemic on psychological wellbeing are yet to be realised, but will be profound, so we assume demand for our solution will inevitably increase. The future of MindConnect from the hackathon stage where we have developed an MVP and conducted alpha testing towards app store and implementation.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown